css: src/main/content/jcr_root/content/oauth-demo/static/css/output.css
.PHONY=css

src/main/content/jcr_root/content/oauth-demo/static/css/output.css: src/main/frontend/input.css
	tailwindcss --input $< --output $@
